project_id = "crypto-watcher-operational"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 15

[db.pooler]
enabled = false
port = 55329

[studio]
enabled = false
port = 55323

[local_smtp]
enabled = false
port = 55324

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[realtime]
enabled = false

[storage]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false
port = 55327
